---

#Damn, this doesn't work on docker containers, as /etc/hosts is a mount & rsync can't rename the copied tmpfile onto it.
- name: Update /etc/hosts
  synchronize: src=/etc/ansible/files/system/hosts dest=/etc/hosts
  tags: etc-hosts,docker-skip

- name: Update root .bashrc
  synchronize: src=/etc/ansible/files/root/.bashrc dest=/root/
  tags: bashrc-root

- name: Update root .bashrc_aliases
  synchronize: src=/etc/ansible/files/root/.bashrc_aliases dest=/root/
  tags: aliases-root
