---
- hosts: "{{ hostgroups }}"
  remote_user: root

  vars:
    facts_on: 'yes'  #Override using command line --extra-vars 'facts_on=no'
  vars_files:
    - vars/soe_vars.yml
    - ~/.ansible_vault.yml
    #- /etc/ansible/vars/default_vars.yml

  gather_facts: "{{ facts_on }}"
  tasks:
    - debug:
        msg: "Facts_on = {{ facts_on }}"
      tags: debug

    - debug:
        msg: "System {{ inventory_hostname }} has ansible_os_family {{ansible_os_family}}, ansible_distribution {{ansible_distribution}}, ansible_distribution_major_version {{ansible_distribution_major_version}}."
      when: facts_on == 'yes'
      tags: debug

    - import_tasks: /etc/ansible/tasks/connect-new-host.yml              #connect new machine
      when:
        - ('il-duce' not in inventory_hostname)
        - facts_on == 'no'

    - import_tasks: /etc/ansible/tasks/ansible-requirements.yml          #install python2-dnf, python-apt requirements.
      when: ('il-duce' not in inventory_hostname) and facts_on == 'yes'

    - import_tasks: /etc/ansible/tasks/network.yml			 #setup networking & hostname